--luacheck:ignore 131
allow_defined_top = true
max_line_length = 999
new_globals = {
   "actor_menu",
   "ActorMenu",
   "alife_clone_weapon",
   "alife_create_item",
   "alife_object",
   "alife_release",
   "bind_campfire",
   "CreateTimeEvent",
   "db",
   "DIK_keys",
   "dik_to_bind",
   "exec_console_cmd",
   "game_relations",
   "game",
   "gameplay_disguise",
   "get_object_by_id",
   "ini_sys",
   "ish_campfire_debug",
   "IsWeapon",
   "item_weapon",
   "item_weapon",
   "key_bindings",
   "key_state",
   "level_weathers",
   "level",
   "on_game_start",
   "parse_list",
   "printf",
   "RegisterScriptCallback",
   "relation_registry",
   "RemoveTimeEvent",
   "SIMBOARD",
   "strformat",
   "surge_manager",
   "time_global",
   "time_infinite",
   "ui_mcm",
   "user_name",
   "utils_data",
   "utils_item",
   "xr_effects"
}
ignore = {
   "131/on_game_start",
   "212/typ"
}
